services:
  cv:
    build:
      context: .
      target: release
    volumes:
      - cv:/app

  worker:
    depends_on:
      - cv
    image: nginx:1.23.2-alpine
    ports:
      - 8080:80
    volumes:
      - ./config/nginx/worker.conf:/etc/nginx/conf.d/default.conf
      - cv:/usr/share/nginx/html

volumes:
  cv: